// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: alloc.proto
#ifndef GRPC_alloc_2eproto__INCLUDED
#define GRPC_alloc_2eproto__INCLUDED

#include "alloc.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

class CudaAllocator final {
 public:
  static constexpr char const* service_full_name() {
    return "CudaAllocator";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Malloc(::grpc::ClientContext* context, const ::MallocRequest& request, ::MallocReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MallocReply>> AsyncMalloc(::grpc::ClientContext* context, const ::MallocRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MallocReply>>(AsyncMallocRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MallocReply>> PrepareAsyncMalloc(::grpc::ClientContext* context, const ::MallocRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::MallocReply>>(PrepareAsyncMallocRaw(context, request, cq));
    }
    virtual ::grpc::Status Free(::grpc::ClientContext* context, const ::FreeRequest& request, ::FreeReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FreeReply>> AsyncFree(::grpc::ClientContext* context, const ::FreeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FreeReply>>(AsyncFreeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FreeReply>> PrepareAsyncFree(::grpc::ClientContext* context, const ::FreeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::FreeReply>>(PrepareAsyncFreeRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Malloc(::grpc::ClientContext* context, const ::MallocRequest* request, ::MallocReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Malloc(::grpc::ClientContext* context, const ::MallocRequest* request, ::MallocReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Malloc(::grpc::ClientContext* context, const ::MallocRequest* request, ::MallocReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void Free(::grpc::ClientContext* context, const ::FreeRequest* request, ::FreeReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Free(::grpc::ClientContext* context, const ::FreeRequest* request, ::FreeReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Free(::grpc::ClientContext* context, const ::FreeRequest* request, ::FreeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MallocReply>* AsyncMallocRaw(::grpc::ClientContext* context, const ::MallocRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::MallocReply>* PrepareAsyncMallocRaw(::grpc::ClientContext* context, const ::MallocRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FreeReply>* AsyncFreeRaw(::grpc::ClientContext* context, const ::FreeRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::FreeReply>* PrepareAsyncFreeRaw(::grpc::ClientContext* context, const ::FreeRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Malloc(::grpc::ClientContext* context, const ::MallocRequest& request, ::MallocReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MallocReply>> AsyncMalloc(::grpc::ClientContext* context, const ::MallocRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MallocReply>>(AsyncMallocRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MallocReply>> PrepareAsyncMalloc(::grpc::ClientContext* context, const ::MallocRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::MallocReply>>(PrepareAsyncMallocRaw(context, request, cq));
    }
    ::grpc::Status Free(::grpc::ClientContext* context, const ::FreeRequest& request, ::FreeReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FreeReply>> AsyncFree(::grpc::ClientContext* context, const ::FreeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FreeReply>>(AsyncFreeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FreeReply>> PrepareAsyncFree(::grpc::ClientContext* context, const ::FreeRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::FreeReply>>(PrepareAsyncFreeRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Malloc(::grpc::ClientContext* context, const ::MallocRequest* request, ::MallocReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Malloc(::grpc::ClientContext* context, const ::MallocRequest* request, ::MallocReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Malloc(::grpc::ClientContext* context, const ::MallocRequest* request, ::MallocReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void Free(::grpc::ClientContext* context, const ::FreeRequest* request, ::FreeReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Free(::grpc::ClientContext* context, const ::FreeRequest* request, ::FreeReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Free(::grpc::ClientContext* context, const ::FreeRequest* request, ::FreeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::MallocReply>* AsyncMallocRaw(::grpc::ClientContext* context, const ::MallocRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::MallocReply>* PrepareAsyncMallocRaw(::grpc::ClientContext* context, const ::MallocRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FreeReply>* AsyncFreeRaw(::grpc::ClientContext* context, const ::FreeRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::FreeReply>* PrepareAsyncFreeRaw(::grpc::ClientContext* context, const ::FreeRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Malloc_;
    const ::grpc::internal::RpcMethod rpcmethod_Free_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Malloc(::grpc::ServerContext* context, const ::MallocRequest* request, ::MallocReply* response);
    virtual ::grpc::Status Free(::grpc::ServerContext* context, const ::FreeRequest* request, ::FreeReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Malloc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Malloc() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Malloc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Malloc(::grpc::ServerContext* /*context*/, const ::MallocRequest* /*request*/, ::MallocReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMalloc(::grpc::ServerContext* context, ::MallocRequest* request, ::grpc::ServerAsyncResponseWriter< ::MallocReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Free : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Free() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Free() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Free(::grpc::ServerContext* /*context*/, const ::FreeRequest* /*request*/, ::FreeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFree(::grpc::ServerContext* context, ::FreeRequest* request, ::grpc::ServerAsyncResponseWriter< ::FreeReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Malloc<WithAsyncMethod_Free<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Malloc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Malloc() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::MallocRequest, ::MallocReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::MallocRequest* request, ::MallocReply* response) { return this->Malloc(context, request, response); }));}
    void SetMessageAllocatorFor_Malloc(
        ::grpc::experimental::MessageAllocator< ::MallocRequest, ::MallocReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::MallocRequest, ::MallocReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Malloc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Malloc(::grpc::ServerContext* /*context*/, const ::MallocRequest* /*request*/, ::MallocReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Malloc(
      ::grpc::CallbackServerContext* /*context*/, const ::MallocRequest* /*request*/, ::MallocReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Malloc(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::MallocRequest* /*request*/, ::MallocReply* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Free : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Free() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::FreeRequest, ::FreeReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::FreeRequest* request, ::FreeReply* response) { return this->Free(context, request, response); }));}
    void SetMessageAllocatorFor_Free(
        ::grpc::experimental::MessageAllocator< ::FreeRequest, ::FreeReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::FreeRequest, ::FreeReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Free() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Free(::grpc::ServerContext* /*context*/, const ::FreeRequest* /*request*/, ::FreeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Free(
      ::grpc::CallbackServerContext* /*context*/, const ::FreeRequest* /*request*/, ::FreeReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Free(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::FreeRequest* /*request*/, ::FreeReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Malloc<ExperimentalWithCallbackMethod_Free<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Malloc<ExperimentalWithCallbackMethod_Free<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Malloc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Malloc() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Malloc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Malloc(::grpc::ServerContext* /*context*/, const ::MallocRequest* /*request*/, ::MallocReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Free : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Free() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Free() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Free(::grpc::ServerContext* /*context*/, const ::FreeRequest* /*request*/, ::FreeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Malloc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Malloc() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Malloc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Malloc(::grpc::ServerContext* /*context*/, const ::MallocRequest* /*request*/, ::MallocReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestMalloc(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Free : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Free() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Free() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Free(::grpc::ServerContext* /*context*/, const ::FreeRequest* /*request*/, ::FreeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestFree(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Malloc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Malloc() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Malloc(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Malloc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Malloc(::grpc::ServerContext* /*context*/, const ::MallocRequest* /*request*/, ::MallocReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Malloc(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Malloc(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Free : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Free() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Free(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Free() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Free(::grpc::ServerContext* /*context*/, const ::FreeRequest* /*request*/, ::FreeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Free(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Free(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Malloc : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Malloc() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::MallocRequest, ::MallocReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::MallocRequest, ::MallocReply>* streamer) {
                       return this->StreamedMalloc(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Malloc() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Malloc(::grpc::ServerContext* /*context*/, const ::MallocRequest* /*request*/, ::MallocReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedMalloc(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::MallocRequest,::MallocReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Free : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Free() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::FreeRequest, ::FreeReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::FreeRequest, ::FreeReply>* streamer) {
                       return this->StreamedFree(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Free() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Free(::grpc::ServerContext* /*context*/, const ::FreeRequest* /*request*/, ::FreeReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedFree(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::FreeRequest,::FreeReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Malloc<WithStreamedUnaryMethod_Free<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Malloc<WithStreamedUnaryMethod_Free<Service > > StreamedService;
};


#endif  // GRPC_alloc_2eproto__INCLUDED
